// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6oPpiWRIokN7E-oCwypFWJz4cy4mlUA',
    appId: '1:953815718685:web:42a68653ebce07b45e5ff4',
    messagingSenderId: '953815718685',
    projectId: 'gdsc-solutionchanllenge2024',
    authDomain: 'gdsc-solutionchanllenge2024.firebaseapp.com',
    storageBucket: 'gdsc-solutionchanllenge2024.appspot.com',
    measurementId: 'G-R65SSGCXC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3ZAdcvz_wD136KGrgQyKq47HEPCIf3M',
    appId: '1:953815718685:android:c82f2904c8558ab35e5ff4',
    messagingSenderId: '953815718685',
    projectId: 'gdsc-solutionchanllenge2024',
    storageBucket: 'gdsc-solutionchanllenge2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWURSaHieSxA_m7TNMyh1AILfxGAZtSA',
    appId: '1:953815718685:ios:7aa54bedc636654a5e5ff4',
    messagingSenderId: '953815718685',
    projectId: 'gdsc-solutionchanllenge2024',
    storageBucket: 'gdsc-solutionchanllenge2024.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWURSaHieSxA_m7TNMyh1AILfxGAZtSA',
    appId: '1:953815718685:ios:be6c0f414c46cd375e5ff4',
    messagingSenderId: '953815718685',
    projectId: 'gdsc-solutionchanllenge2024',
    storageBucket: 'gdsc-solutionchanllenge2024.appspot.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
